micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/key
    driverClassName: org.postgresql.Driver
    username: key
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update


clients:
  erp-itau: http://localhost:9091/api/v1